#pragma config(Sensor, in1,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in2,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in3,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Sensor, in8,    mypot,          sensorPotentiometer)
#pragma config(Sensor, dgtl5,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl10, touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl11, sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port7,           armMotor,      tmotorVex269, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------------------------------*\
|*   This program makes the robot turn around itself until it the sonar sensor pickups up a signal   *|
|*                of an object. It drives toward the object tries to knock it down.                  *|
|*      After knocking down the object it tries to find other objects that are near the robot.       *|
|*            If the robot drives over the border it turns around back to the arena.                 *|
|*    MOTORS & SENSORS:                                                                              *|
|*    [I/O Port]           [Name]              [Type]                [Description]                   *|
|*    Motor   - Port 2     leftMotor           VEX 3-wire module     Right side motor                *|
|*    Motor   - Port 3     rightMotor          VEX 3-wire module     Left side motor                 *|
|*    Motor   - Port 7     armMotor            VEX 3-wire module     Arm motor                       *|6
|*    Analog  - Port 1     lineFollowerRIGHT   VEX Light Sensor      Front-right, facing down        *|
|*    Analog  - Port 2     lineFollowerCENTER  VEX Light Sensor      Front-center, facing down       *|
|*    Analog  - Port 3     lineFollowerLEFT    VEX Light Sensor      Front-left, facing down         *|
|*    Analog  - Port 4     potentioSensor      VEX Quadrature enc.   Potentiometer on the side       *|
|*    Digital - Port 5     sonarSensor         VEX Sonar Sensor      Front mounted, front facing     *|
\*----------------------------------------------------------------------------------------------4246-*/


int highpower = 50;
int lowpower = 30;
int nopower = 0;
int distance = 50;
int knockDistance = 20;
int counter = 0;
int threshold = 2100;
float someDegree = 113.097/31.41; // How far the wheels have to go for 1 degree
float oneDegree = someDegree - 0.5; // fix the distance for one degree
float degree;
void find()
{
	while(SensorValue[sonarSensor] > distance)
	{
		motor[leftMotor] = lowpower;
		motor[rightMotor] = -lowpower;
	}
}
void stopMotors()
{
	motor[leftMotor] = nopower;
	motor[rightMotor] = nopower;
}
void reach()
{
	while(SensorValue[sonarSensor] > knockDistance && SensorValue[lineFollowerCENTER] > threshold)
	{
		motor[leftMotor] = highpower;
		motor[rightMotor] = highpower;
	}
}
void turnright(int degrees) //function for turning right
{
	degree = oneDegree * degrees; // calcualting how many degrees it needs to turn
	while(abs(SensorValue[rightEncoder]) < degree) // While the right encoder is less than distance:
  {
		// spins right around itself
		motor[rightMotor] = -63;		    // Right Motor is run at power level -63
		motor[leftMotor]  = 63;		    // Left Motor is run at power level 63
  }
}
void knock()
{
	motor[leftMotor] = lowpower;
	motor[rightMotor] = -lowpower;
	wait1Msec(500);
	stopMotors();
	while (SensorValue[mypot] > 1) {
		motor[armMotor] = -highpower;
	}
	motor[armMotor] = nopower;
	motor[leftMotor] = -highpower;
	motor[rightMotor] = highpower;
	wait1Msec(1000);
	stopMotors();
	while (SensorValue[mypot] < 700) {
		motor[armMotor] = highpower;
	}
	motor[armMotor] = nopower;
}

task e_stop()
{
	while(true) {
		if(SensorValue(touchSensor) == 1)	{
			StopAllTasks();
		}
		wait1Msec(10);
  }
}
task adal()
{




}
task tof()	{
	while(true)
	{
		if(SensorValue[lineFollowerCENTER] > threshold) {
				StopTask(adal);
				wait1Msec(2000);
      	/*SensorValue[rightEncoder]  = 0;
      	turnright(170);*/
      	StartTask(adal);
		}
		wait1Msec(10);
	}
}

task main()
{
	wait1Msec(10000);
	StartTask(e_stop);
  while(counter < 3)
	{
		find();
		stopMotors();
		reach();
		if(SensorValue[sonarSensor] < knockDistance){
			stopMotors();
			knock();
			counter++;
		}
			else if(SensorValue[lineFollowerCENTER] < threshold) {
      	SensorValue[rightEncoder]  = 0;
      	turnright(170);
      	motor[leftMotor] = highpower;
      	motor[rightMotor] = highpower;
      	wait1Msec(500);
		}
	}
}
